version: "3.9"

services:
  xhs-auto-worker:
    build:
      context: ./_src/XHS-Downloader-NAS-main

  x-auto-downloader:
    build:
      context: ./_src/x-auto-download-nas-main

  pixiv-auto-downloader:
    build:
      context: ./_src/pixiv-auto-download-nas-main

  pixiv-oauth:
    build:
      context: ./_src/pixiv-auto-download-nas-main
