version: "3.9"

services:
  xhs-api:
    image: ghcr.io/joeanamier/xhs-downloader:2.7
    container_name: xhs-api
    ports:
      - "13001:5556"
    volumes:
      - /volume2/docker/nas-auto-download-integrated/xhs/volumes:/app/Volume
      - /volume2/se-p/小红书:/xhs
    tty: true
    stdin_open: true
    command: bash -lc "python main.py api 2>&1 | tee -a /app/Volume/xhs-api.log"
    restart: unless-stopped

  nas-auto-download:
    image: ghcr.io/ccawmiku/nas-auto-download-integrated:v1.8.2-dev
    container_name: nas-auto-download
    init: true
    depends_on:
      - xhs-api
    ports:
      - "14001:14001"
    volumes:
      - /volume2/docker/nas-auto-download-integrated/xhs/volumes:/xhs-volume
      - /volume2/docker/nas-auto-download-integrated/xhs/auto/config:/config/xhs
      - /volume2/docker/nas-auto-download-integrated/xhs/auto/queue:/queue/xhs
      - /volume2/docker/nas-auto-download-integrated/xhs/auto/state:/state/xhs
      - /volume2/se-p/小红书:/xhs
      - /volume2/docker/nas-auto-download-integrated/x/config:/config/x
      - /volume2/docker/nas-auto-download-integrated/x/state:/state/x
      - /volume2/docker/nas-auto-download-integrated/x/downloads-metadata:/downloads/x/downloads-metadata
      - /volume2/se-p/x-p:/downloads/x/images
      - /volume2/se-v/x-v:/downloads/x/videos
      - /volume2/docker/nas-auto-download-integrated/pixiv/config:/config/pixiv
      - /volume2/docker/nas-auto-download-integrated/pixiv/state:/state/pixiv
      - /volume2/se-p/pixiv:/downloads/pixiv
      - /volume2/docker/nas-auto-download-integrated/douyin/config:/config/douyin
      - /volume2/docker/nas-auto-download-integrated/douyin/f2/database:/state/douyin/f2
      - /volume1/douyin:/douyin
    restart: unless-stopped
